services:
  mysql-container:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: DatabaseEssai
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-container:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql-container
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
