version: '3.8'

services:
  mysql-container:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: DatabaseEss
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  springboot-container:
    build: .
    container_name: springboot-container
    depends_on:
      - mysql-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/DatabaseEss?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      FLASK_API_URL: http://localhost:5000  # Make sure Flask API URL is correct
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
